version: '3.9'


services:

  db:
    image: postgres:14.3-alpine3.15
#    build: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flask_db


